version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "dogs-repo"
          ContainerPort: 80
#Hooks:
#- BeforeInstall: "BeforeInstallHookFunctionName"
#- AfterInstall: "AfterInstallHookFunctionName"
#- AfterAllowTestTraffic: "AfterAllowTestTrafficHookFunctionName"
#- BeforeAllowTraffic: "BeforeAllowTrafficHookFunctionName"
#- AfterAllowTraffic: "AfterAllowTrafficHookFunctionName"
